repos:
  # Core hygiene hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: ['--autofix', '--indent=2']
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=20480']
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

  # Secrets detection
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            docs/.*|
            .*\.lock$|
            .*\.min\.js$
          )

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: \.sh$
        args: ['-S', 'warning']

  # Shell script formatting
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
        args: ['-i', '2', '-ci', '-bn', '-sr', '-w']
        files: \.sh$

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

  # Python linting and formatting (if Python files exist)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.1
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix']
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi]

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ['-d', '{extends: default, rules: {line-length: {max: 120}, truthy: disable}}']

  # Prevent direct commits to protected branches
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']

# Configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: '3.0.0'
