---
name: hygiene

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install --upgrade pre-commit detect-secrets

      - run: pre-commit validate-config
      - run: pre-commit run --all-files
