name: Pre-commit Autoupdate

on:
  schedule:
    - cron: "0 8 1 * *"
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/pre-commit-autoupdate
          delete-branch: true
          title: "chore(pre-commit): monthly autoupdate"
          body: |
            ## Summary
            Automated monthly update of pre-commit hooks to latest versions.

            ## Changes
            Updated `.pre-commit-config.yaml` with latest hook versions.

            ## Test Plan
            CI hygiene workflow will validate all hooks are functional.
          commit-message: |
            chore(pre-commit): monthly autoupdate

            Signed-off-by: Lazarus Laboratories <dev@lazarus-labs.com>
          author: Lazarus Laboratories Bot <dev@lazarus-labs.com>
          signoff: true
